# Generated by Django 5.2.10 on 2026-01-11 14:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('rows_count', models.PositiveIntegerField()),
                ('seats_per_row', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('poster_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vip_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Обычное'), ('VIP', 'VIP'), ('DISABLED', 'Отключено')], default='STANDARD', max_length=16)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('CANCELLED', 'Отменён')], default='ACTIVE', max_length=16)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cinema.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена')], default='CONFIRMED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cinema.session')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_snapshot', models.PositiveIntegerField()),
                ('seat_snapshot', models.PositiveIntegerField()),
                ('seat_type_snapshot', models.CharField(choices=[('STANDARD', 'Обычное'), ('VIP', 'VIP'), ('DISABLED', 'Отключено')], max_length=16)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cinema.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['hall', 'row', 'number'], name='cinema_seat_hall_id_892a7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row', 'number'), name='uniq_seat_in_hall'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['hall', 'starts_at'], name='cinema_sess_hall_id_15a074_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['starts_at'], name='cinema_sess_starts__642bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['session'], name='cinema_tick_session_a5c1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['code'], name='cinema_tick_code_ca4ce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('session', 'seat'), name='uniq_ticket_seat_in_session'),
        ),
    ]
